### ISSUE TITLE
There are no  (resnet50-19c8e357.pth) files.

### ISSUE THREAD

**Issue by Henkwu** [cswluo/SEF#2]
Traceback (most recent call last):
  File "main.py", line 146, in <module>
    state_params = torch.load(state_dict_path)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 571, in load
    with _open_file_like(f, 'rb') as opened_file:  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 229, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/serialization.py", line 210, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/the/vanilla/resnet/models/resnet50-19c8e357.pth

**Comment by Ritabrata-Chakraborty** [comment]
Did you figure out anything?
